name: Build the application

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@master

      - name: Fetch dependencies from cache
        id: cache
        uses: actions/cache@v2
        with:
          path: Carthage
          key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
          restore-keys: |
            ${{ runner.os }}-carthage-

      - name: Install carthage dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: carthage update --platform macOS

      - name: Build application
        if: success()
        run: |
          xcodebuild \
            -scheme Stats \
            -destination 'platform=OS X,arch=x86_64' \
            -configuration Release \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO
